import React ,{useEffect,useRef} from "react"
import {gsap} from "gsap"
import{ScrollTrigger} from "gsap/ScrollTrigger"
import Lenis from "@studio-freight/lenis"
import About from "./About.tsx"
import Certificates from "./Certificates.tsx"
import Contact from "./Contact.tsx"
import CustomerCursor from "./CustomerCursor.tsx"
import Hero from "./Hero.tsx"
import Marquee from "./Marquee.tsx"
import Navbar from "./Navbar.tsx"
import Navigation from "./Navigation.tsx"
import ProgressBar from "./ProgressBar.tsx"
import Skills from "./Skills.tsx"
import SpaceBackground from "./SpaceBackground.tsx"
import SVGLLineAnimation from "./SVGLLineAnimation.tsx"
import work from "./Work.tsx"